### ISSUE TITLE
After update to 10.13.2/3, 'does printf work??' during boot 

### ISSUE THREAD

**Issue by yaozaiyu** [al3xtjames/Clover#2]
I have tried

OsxAptioDrv2
OsxAptioDrv3
OsxAptioDrv + Test2
OsxAptioDrv-free2000
AptioMemoryFix
All tried multiple times, all failed.

**Comment by al3xtjames** [comment]
I don't see how this is related to this fork. Could you elaborate?

**Comment by yaozaiyu** [comment]
sorry,i want to find the writer of clover，and the  problem‘s url is https://github.com/wmchris/DellXPS15-9550-OSX/issues/64。
 if you know the person can solve the problem，please tell me，thanks！
